"""End-to-end test against a checked-in, realistic synthetic photo.

No real camera/photo is available yet (markers aren't even printed --
see README Milestones), so tests/fixtures/synthetic_photo.png is the
closest available approximation: a rendered marker layout warped by a
known homography and degraded with the failure modes README's "Known
failure modes" section names as dominant -- uneven exposure, blur,
sensor noise -- generated by generate_synthetic_photo_fixture.py and
checked in rather than regenerated per test run.

Pinning the image (instead of rendering it fresh each run) is the
point: this makes the test a true regression test for detect.py and
solve.py. If either changes and produces a different result against
this exact photo, that's a real signal to investigate -- not noise from
a freshly-rerolled random seed masking or manufacturing a difference.
"""

import json
from pathlib import Path

import cv2
import numpy as np
import pytest

from boresight.detect import detect_markers
from boresight.solve import solve

FIXTURE_DIR = Path(__file__).parent / "fixtures"
IMAGE_PATH = FIXTURE_DIR / "synthetic_photo.png"
METADATA_PATH = FIXTURE_DIR / "synthetic_photo.json"


def _apply_homography(
    homography: np.ndarray, points: list[tuple[float, float]]
) -> list[tuple[float, float]]:
    pts = np.array(points, dtype=np.float64)
    homogeneous = np.hstack([pts, np.ones((len(pts), 1))])
    projected = homogeneous @ homography.T
    projected /= projected[:, 2:3]
    return [(float(x), float(y)) for x, y in projected[:, :2]]


def _marker_corners_mm(
    top_left: tuple[float, float], size: float
) -> list[tuple[float, float]]:
    x, y = top_left
    return [(x, y), (x + size, y), (x + size, y + size), (x, y + size)]


def test_full_pipeline_recovers_aim_point_from_a_realistic_synthetic_photo():
    metadata = json.loads(METADATA_PATH.read_text())
    image_size = tuple(metadata["image_size"])
    marker_size_mm = metadata["marker_size_mm"]
    marker_layout_mm = {
        int(marker_id): tuple(corner)
        for marker_id, corner in metadata["marker_layout_mm"].items()
    }
    ground_truth_homography = np.array(metadata["ground_truth_homography"])

    image = cv2.imread(str(IMAGE_PATH), cv2.IMREAD_GRAYSCALE)
    assert image is not None, f"fixture image not found at {IMAGE_PATH}"

    detected = detect_markers(image)
    # At this marker size (80px) and this fixture's degradation level,
    # ArUco decoding is robust enough that all 8 typically still survive
    # -- verified by hand up to 2.5x this noise/blur severity while
    # tuning generate_synthetic_photo_fixture.py. The floor of >=1 is a
    # pipeline guarantee (one fully-visible marker's 4 corners are
    # enough to solve), not a claim that this fixture demonstrates
    # dropout; real dropout needs occlusion/framing loss this
    # image-level degradation model doesn't reproduce.
    assert len(detected) >= 1, "expected at least one marker to survive degradation"

    correspondences = []
    for marker in detected:
        known_corners_mm = _marker_corners_mm(
            marker_layout_mm[marker.marker_id], marker_size_mm
        )
        for screen_point, image_point in zip(
            known_corners_mm, marker.corners, strict=True
        ):
            correspondences.append(
                (screen_point, (float(image_point[0]), float(image_point[1])))
            )

    result = solve(correspondences, image_size)

    true_inverse = np.linalg.inv(ground_truth_homography)
    image_centre = [(image_size[0] / 2.0, image_size[1] / 2.0)]
    expected_aim_point = _apply_homography(true_inverse, image_centre)[0]

    # Looser than stage 2's clean-render tolerance (1.5mm): exposure
    # gradient, blur, and noise perturb detected corner positions beyond
    # what a clean warpPerspective render introduces. Observed ~1.3mm
    # against this fixture; 3mm leaves margin without masking a real
    # regression.
    assert result.aim_point_mm == pytest.approx(expected_aim_point, abs=3.0)
